// JavaScript Document

const products = new Map([
	["1", ["Keyboard 1PSR-EW425", "images/keyboard1.jpg", "$500.00", "The 1PSR-EW425 is a versatile and dynamic 76-key portable keyboard designed for musicians of all levels. With its wide range of features, this keyboard offers a great balance between performance and affordability.<br><br>Featuring a comprehensive library of high-quality sounds, including pianos, strings, brass, and more, the 1PSR-EW425 allows you to explore a variety of musical styles with ease. Its 76 touch-sensitive keys provide a realistic playing experience, while the built-in speakers deliver rich and immersive sound.<br><br>The keyboard also features a range of performance-enhancing features, such as the Yamaha Education Suite, which helps beginners learn to play quickly and easily. Additionally, the keyboard's USB connectivity allows you to connect to a computer or mobile device for use with music production software or educational apps.<br><br>Whether you're a beginner just starting out or an experienced player looking for a portable and versatile instrument, the 1PSR-EW425 is sure to inspire creativity and musical expression."]],
	["2", ["Keyboard CK88", "images/keyboard2.jpg", "$1500.00", "The CK88 musical keyboard is a versatile and powerful instrument designed for musicians of all levels. Featuring 88 keys, the CK88 provides a full range of notes, allowing for expressive playing and intricate compositions. It offers a range of features to enhance your music-making, including touch-sensitive keys for dynamic control, built-in sounds and voices, and connectivity options for MIDI and audio. The CK88's sleek and ergonomic design makes it a great choice for home studios, live performances, or music production on the go. Whether you're a beginner or a seasoned pro, the CK88 keyboard is sure to inspire your creativity and take your music to the next level."]],
	["3", ["Upright U1", "images/piano1.jpg", "$14500.00", "The Yamaha U1 is a popular upright piano known for its quality craftsmanship and sound. It stands at around 48 inches tall and is designed to deliver a rich and resonant tone. The U1 is often praised for its durability and reliability, making it a favorite among students, teachers, and professional musicians alike. Its responsive action and consistent touch make it a pleasure to play, and its classic design fits well in both home and studio settings. Overall, the Yamaha U1 is recognized for its superb sound quality, playability, and value, making it a highly sought-after instrument in the piano world."]],
	["4", ["Grand GB1K", "images/piano3.jpg", "$16000.00", "The Yamaha GB1K is a baby grand piano that offers the rich sound and playability of a grand piano in a more compact size. It is approximately 5 feet in length, making it suitable for smaller spaces while still delivering a full, resonant tone. The GB1K is known for its high-quality construction and materials, ensuring durability and reliability. It features Yamaha's renowned craftsmanship and attention to detail, resulting in a piano that is both beautiful and musically satisfying. The GB1K is often chosen by pianists looking for a grand piano experience in a more space-conscious package."]],
	["5", ["Keyboard Pedal FC3A", "images/pedal.jpg", "$70.00", "The Yamaha FC3A is a piano-style sustain pedal designed for electronic keyboards and digital pianos. It's built to replicate the feel and response of a traditional acoustic piano pedal, offering a realistic playing experience. The pedal is typically made of high-quality materials for durability and longevity.<br><br>One of the key features of the FC3A is its half-damper capability, which means it can detect and respond to varying levels of pedal pressure, allowing for more nuanced and expressive playing. This makes it ideal for musicians who want to achieve a more authentic piano performance on their digital instrument.<br><br>The FC3A connects to the keyboard or digital piano via a standard 1/4-inch jack, and it usually includes a rubber bottom to prevent slipping during use. Overall, the Yamaha FC3A is a reliable and popular choice for keyboardists looking for a high-quality sustain pedal."]],
	["6", ["Guitar CGS102AII ", "images/guitar1.jpg", "$140", "The Guitar CGS102AII is a classical acoustic guitar designed for beginners and students. It features a full-size body, typically made of spruce for the top and mahogany for the back and sides, though specific materials can vary. The neck is usually made of nato or mahogany, with a rosewood fretboard.<br><br>This guitar is known for its playability and affordability, making it a popular choice for those just starting to learn the instrument. It produces a warm, mellow tone that is characteristic of classical guitars, making it suitable for classical, flamenco, and other acoustic styles."]],
	["7", ["Guitar FG800J Acoustic", "images/guitar2.jpg", "$229.00", "The Yamaha FG800J is a dreadnought acoustic guitar known for its quality at an affordable price. It features a solid spruce top, nato or mahogany back and sides, and a comfortable neck with a rosewood fretboard. The guitar delivers a balanced, dynamic sound with clear highs and robust lows, making it suitable for various playing styles. With its durable construction and comfortable playability, the FG800J is a popular choice for beginners and experienced players alike."]],
	["8", ["Guitar NTX5", "images/guitar3.jpg", "$3,020.00", "The Yamaha NTX5 is a modern nylon-string acoustic-electric guitar with a comfortable, slim body design that appeals to players used to steel-string or electric guitars. It features a solid spruce top for a bright tone, and typically has rosewood or ovangkol back and sides for warmth. The slim neck and low action make it easy to play, and it's equipped with high-quality electronics for amplified performance. Overall, it's a versatile and comfortable guitar for players of all levels."]],
	["9", ["Guitar NTX1", "images/guitar4.jpg", "$460.00", "The Yamaha NTX1 is a nylon-string acoustic-electric guitar designed for players seeking a comfortable, easy-to-play instrument with a traditional nylon-string sound. It features a modern body shape with a slim profile and cutaway design for easy access to the upper frets. The solid spruce top produces a clear, balanced tone, while the nato or okoume back and sides provide a warm, mellow sound. The guitar has a slim, comfortable neck profile made of nato or okoume, topped with a rosewood or walnut fretboard. Equipped with Yamaha's Atmosfeel pickup and preamp system, the NTX1 delivers a natural, transparent sound when amplified, making it suitable for live performances and recording. Overall, the Yamaha NTX1 offers a versatile and comfortable playing experience for players of all levels."]],
	["10", ["Headphone YH-E700B", "images/headphone1.jpg", "$355.00", "The Yamaha YH-E700A is a wireless noise-canceling headphone designed for high-quality sound and comfort during extended listening. It features high-resolution audio playback for clear, detailed sound and a balanced profile suitable for various music genres. With adjustable active noise cancellation (ANC), you can customize the level of ambient noise reduction to suit your environment. The headphones are designed for comfort with soft ear cushions and a lightweight build. They support Bluetooth connectivity and high-quality audio codecs for wireless streaming from compatible devices. The YH-E700A offers up to 35 hours of battery life with ANC enabled and has intuitive touch controls on the ear cups for easy operation. Overall, it's a premium headphone option for immersive, long-lasting listening experiences."]],
	["11", ["Wireless Eardbuds TW-ES5A", "images/earbud1.jpg", "$190.00", "The Yamaha TW-ES5A are wireless earbuds designed to provide high-quality sound and convenience. They offer clear and detailed audio with a balanced sound profile and good bass response. Using Bluetooth technology, these earbuds can wirelessly connect to your devices, such as smartphones and tablets, for tangle-free listening. They are designed for comfort with ergonomic ear tips for a secure fit, reducing outside noise and improving sound isolation. The earbuds provide several hours of continuous playback on a single charge, with the included charging case offering additional battery life. Touch-sensitive controls make it easy to play/pause music, adjust the volume, skip tracks, and answer calls. The earbuds are also water-resistant, suitable for use during workouts or in rainy weather. Overall, the Yamaha TW-ES5A earbuds offer a premium wireless audio experience with a focus on sound quality, comfort, and convenience."]],
	["12", ["Microphone YCMO1", "images/mic1.jpg", "$120.00", "The Yamaha YCMO1 microphone is a versatile and high-quality option for professional and home recording applications. It offers exceptional audio quality, capturing vocals and instruments with clarity and accuracy. With multiple pickup patterns (cardioid, omnidirectional, and figure-8), it is suitable for a wide range of recording scenarios, from solo performances to group recordings and ambient room miking. The microphone is built to last, with a rugged design, and comes with a shock mount and carrying case for added convenience and protection. Despite its professional-grade features, the YCMO1 is competitively priced, making it an excellent value for musicians, podcasters, and content creators looking to upgrade their recording setup. Overall, the Yamaha YCMO1 microphone provides exceptional sound quality, versatility, and durability at an affordable price point."]],
	["13", ["Microphone AG01", "images/mic2.jpg", "$300.00", "The Yamaha AG01 is a high-quality microphone designed for a variety of recording applications. It is known for its clear and accurate sound reproduction, making it suitable for recording vocals, instruments, and other audio sources with detail and clarity. The AG01 is a versatile microphone that can handle a wide range of recording scenarios, from studio recordings to live performances. It is built to last, with a durable design that can withstand the rigors of regular use. The AG01 may include features such as a cardioid pickup pattern for focused sound capture, a built-in pop filter to reduce plosives, and a shock mount to reduce handling noise. It typically connects to recording devices via a standard XLR cable, ensuring compatibility with a wide range of audio interfaces and mixers. Overall, the Yamaha AG01 is a reliable and versatile microphone that offers excellent sound quality and durability, making it a great choice for professional and amateur musicians alike."]],
	["14", ["Bass Guitar Attitude 30th", "images/bassguitar1.jpg", "$7,000.00", "Whether you should buy the Yamaha Bass Guitar Attitude 30th depends on your needs and preferences as a bass player. The Attitude 30th is designed for comfort and playability, with a sleek neck profile and a contoured body shape. It's known for its powerful and versatile sound, thanks to its active electronics and versatile pickup configuration. Yamaha's reputation for high-quality construction means the Attitude 30th is built to last, making it reliable for gigging and recording. However, it's a premium instrument and may be more expensive than other bass guitars. If you value playability, sound quality, and build quality, and the price is within your budget, the Yamaha Bass Guitar Attitude 30th could be a great investment."]],
	["15", ["Bass Guitar BBNE2", "images/bassguitar2.jpg", "$5,376.00", "The Yamaha BBNE2 is a high-end bass guitar designed in collaboration with renowned bassist Nathan East. It features a classic double-cutaway design with a solid alder body and a bolt-on maple neck. The neck has a slim profile and 21 frets, making it comfortable to play. The BBNE2 is equipped with two custom-designed alnico V pickups controlled by a 3-band active EQ, offering a versatile range of tones. The high-mass bridge design increases sustain and resonance. Known for its rich, warm tone with plenty of low-end punch, the BBNE2 is suitable for various musical styles. Built to a high standard of quality, the BBNE2 ensures reliability and durability on stage and in the studio. Overall, it's a top-of-the-line bass guitar for serious players looking for the best in tone, playability, and build quality."]],
	["16", ["Bass Guitar TRBJP2", "images/bassguitar3.jpg", "$6,500.00", "The Yamaha TRBJP2 is a signature bass guitar created in collaboration with bassist John Patitucci. It features a sleek double-cutaway design with a solid alder body and a bolt-on maple neck. The neck has a slim profile and 24 frets, offering excellent playability. Equipped with custom-designed Alnico V pickups, the TRBJP2 delivers a versatile range of tones controlled by an active 3-band EQ for precise tone shaping. The high-mass bridge design enhances sustain and resonance, ensuring a rich, full sound. Known for its clear, articulate sound with a tight low end, the TRBJP2 can handle a wide range of musical styles. Built to Yamaha's high standard of quality, the TRBJP2 is reliable and durable. If you're looking for a professional-grade instrument that can handle anything you throw at it, the TRBJP2 is definitely worth considering."]],
	["17", ["Amp THR30IIA", "images/amp1.jpg", "$600.00", "The Yamaha THR30IIA is a versatile acoustic guitar amplifier known for its excellent sound quality and range of features. It accurately reproduces the acoustic characteristics of your guitar with its specially designed speaker system and Virtual Circuitry Modeling (VCM) technology. This technology recreates the sound and feel of classic acoustic amplifiers and microphones. The THR30IIA offers various amp models and effects, including reverb, chorus, and delay, allowing you to customize your sound. Despite its power, it's compact and lightweight, making it easy to transport. It's also battery-powered, providing the flexibility to play anywhere. Bluetooth connectivity allows you to stream music and play along with your favorite tracks. Built with Yamaha's reputation for quality, the THR30IIA is durable and reliable. Overall, it's an excellent choice for acoustic guitarists seeking a portable amplifier with professional sound quality and versatile features."]],
	["18", ["Amp Bag THRBG1", "images/ampbag1.jpg", "$60.00", "It's an amp bag."]],
	["19", ["Snare RLS-1470", "images/snare1.jpg", "$1,106.00", "The Yamaha RLS-1470 is a snare drum known for its high-quality construction and versatile sound. It has a standard size of 14 inches in diameter and 7 inches in depth, offering a balanced sound favored by many drummers. The shell is typically made of maple or birch, providing a warm, rich tone with a good balance of attack and sustain. The drum is equipped with high-quality hardware, including lugs, tension rods, and a snare strainer, designed for durability and precision tuning. The RLS-1470 has a versatile sound suitable for a variety of musical styles, with a crisp, articulate attack and a balanced mix of high, mid, and low frequencies. Available in a range of finishes, the RLS-1470 allows drummers to choose a style that suits their preferences and complements their drum kit. Overall, the Yamaha RLS-1470 is a professional-grade snare drum suitable for drummers of all skill levels, ideal for both studio recording and live performances."]],
	["20", ["Snare LHS-1455", "images/snare2.jpg", "$1,274.00", "The Yamaha LHS-1455 is a snare drum known for its high-quality materials and craftsmanship. It has a standard size of 14 inches in diameter and 5.5 inches in depth, offering a balanced sound and versatility. The shell is typically made of high-quality wood, such as maple or birch, providing a warm, rich tone with a good balance of attack and sustain. Equipped with high-quality hardware, including lugs, tension rods, and a snare strainer, the LHS-1455 is designed for durability and precision tuning. It has a versatile sound suitable for various musical styles, with a crisp, articulate attack and a balanced mix of high, mid, and low frequencies. Available in a range of finishes, the LHS-1455 allows drummers to choose a style that suits their preferences and complements their drum kit. Overall, the Yamaha LHS-1455 is a professional-grade snare drum suitable for drummers of all skill levels, ideal for both studio recording and live performances."]],
	["21", ["Xylo YX-500F", "images/xylo1.jpg", "$2,800.00", "The Yamaha YX-500F is a professional-grade concert xylophone known for its exceptional sound quality and craftsmanship. It features high-quality padauk wood bars that are carefully selected and precision-tuned for excellent tone and resonance. The bars are stained for enhanced appearance and protection. Mounted on a sturdy powder-coated steel frame, the xylophone is stable and durable, with height-adjustable and foldable features for easy transport and storage. Equipped with aluminum resonators, the YX-500F enhances tone and projection, with individually tunable resonators for precise sound adjustment. The xylophone has a 3.5-octave range, covering notes F45 to C88, suitable for various musical styles. It comes with high-quality mallets and a dust cover for protection. Overall, the Yamaha YX-500F is a top choice for professional percussionists, offering exceptional sound quality, durability, and playability for orchestras, concert bands, and other musical ensembles."]],
	["22", ["Tom 9000 Series", "images/tom1.jpg", "$400.00", "The Tama 9000 series is a line of professional drum hardware known for its durability, reliability, and innovative features. It includes a variety of stands for cymbals, snare drums, and toms, designed to be sturdy and stable. The series also features bass drum pedals known for their smooth action and durability, providing a responsive feel for precise playing. Clamps and mounts in the 9000 series are secure and reliable, allowing you to attach your drums and cymbals with confidence. One of the key features of the 9000 series is its adjustability, with many stands and mounts being adjustable to customize the height, angle, and position of your drums and cymbals. Overall, the Tama 9000 series is a popular choice among professional drummers for its durability, reliability, and ability to customize drum kits for individual playing styles."]],
	["23", ["Violin AV20 SG", "images/violin1.jpg", "$3,540.00", "The Yamaha AV20 SG is a student-level violin that offers a solid foundation for beginner players. It features a spruce top and maple back and sides, providing a balanced tone with good projection. The AV20 SG is designed to be easy to play, with a comfortable neck profile and smooth fingerboard. It comes with a bridge, tailpiece, and strings already installed, making it ready to play out of the box. The AV20 SG also includes a lightweight case for easy transport and storage. Overall, the Yamaha AV20 SG is a reliable and affordable option for beginner violinists looking to start their musical journey."]],
	["24", ["Violin AV7 SG", "images/violin2.jpg", "$1,540.00", "The Yamaha AV7 SG is a step-up violin designed for advancing students and amateur musicians. It offers a higher level of craftsmanship and tonal quality compared to beginner-level instruments. The AV7 SG is crafted from select tonewoods, typically spruce for the top and maple for the back, sides, and neck, which are aged and treated to enhance their resonance and projection. Often handmade or semi-handmade, the AV7 SG is constructed with close attention to detail, resulting in a violin that is more responsive and has a richer tone compared to mass-produced instruments. It comes professionally set up, with high-quality strings, a well-fitted bridge, and a properly adjusted soundpost and tailpiece, ensuring optimal playability and tone right out of the box. The AV7 SG may feature an antique-style varnish, giving it a classic and elegant appearance while also protecting the wood and enhancing its resonance. Typically, the AV7 SG comes with a quality bow and a case, providing everything a player needs to start playing immediately. Overall, the Yamaha AV7 SG is a reliable and high-quality violin suitable for advancing students and amateur musicians looking for a violin with improved tone and playability."]],
	["25", ["Keyboard Bag MX88/MOXF8", "images/keyboardbag1.jpg", "$180.00", "It's a keyboard bag."]]
])

function generateGeneratePage(key){
	return function generatePage(){
		localStorage.setItem("name", products.get(key)[0]);
		localStorage.setItem("image", products.get(key)[1]);
		localStorage.setItem("price", products.get(key)[2]);
		localStorage.setItem("desc", products.get(key)[3]);
		window.open("BaseProduct.html");
	}
}


products.forEach((values, keys) => {
	
	var v = values;
	var k = keys;
	
	//create html element to add to page
	const column = document.createElement("div");
	column.setAttribute("class", "col-3");
	const card = document.createElement("div");
	card.setAttribute("class", "card");
	
	
	card.onclick = generateGeneratePage(k); //replace this
	
	column.appendChild(card);
	
	const name = document.createElement("h3");
	name.innerHTML = v[0]//replace this
	const image = document.createElement("img");
	image.setAttribute("class", "fluid-image");
	
	image.src = "images/empty.jpg"; //replace this
	
	if(v[1] !== null){
		image.src = v[1];	
	}
	
	image.alt = "null"; //replace this
	
	card.appendChild(name);
	card.appendChild(image);
	
	const parent = document.getElementById("productlist");
	const child = column;
	parent.appendChild(child);
	
})



